
  
version: "3.7"
services:
  app: 
    build:
      context: ./
      dockerfile: Dockerfile
    image: teste-esfera-web
    container_name: teste-esfera-web
    restart: unless-stopped
    working_dir: /
    ports: 
      - "3000:3000"
    volumes:
      - ./docker-compose/web:/web-teste-esfera-init.d
    networks:
      - integration
networks:
  integration: